-- ============================================================================
-- MusterMate: Remove demo/seed data from an existing database.
-- ============================================================================
-- The demo seeder was removed from the codebase. This script purges the demo
-- organization and its rows (sites, workers, attendance, payments, leaves,
-- notifications, chat, labour submissions) from databases that were previously
-- seeded, so no leftover demo data ships to production.
--
-- IMPORTANT: Run this ONLY against a dev/pre-prod database you own.
--  1. Take a full backup first:
--       pg_dump -U postgres -h localhost mustermate > mustermate_pre_demo_cleanup.sql
--  2. Run this script:
--       psql -U postgres -h localhost -d mustermate -f server/scripts/cleanup_demo.sql
--  3. Verify:
--       SELECT count(*) FROM organizations;           -- no org-101 row
--       SELECT count(*) FROM users WHERE organization_id = 'org-101';  -- 0
-- ============================================================================

BEGIN;

-- Chat messages posted in the demo 'global' / org-101 site channels.
DELETE FROM chat WHERE organization_id = 'org-101';

-- Labour day claims submitted by demo workers.
DELETE FROM labour_submissions WHERE organization_id = 'org-101';

-- Attendance snapshots generated by the demo window.
DELETE FROM attendance WHERE organization_id = 'org-101';

-- Payment logs for demo workers.
DELETE FROM payments WHERE organization_id = 'org-101';

-- Leave requests raised by demo workers.
DELETE FROM leaves WHERE organization_id = 'org-101';

-- Notifications created by the demo seeder.
DELETE FROM notifications WHERE organization_id = 'org-101';

-- Demo workers.
DELETE FROM workers WHERE organization_id = 'org-101';

-- Demo sites (detach any user references first).
UPDATE users SET site_id = NULL WHERE organization_id = 'org-101';
DELETE FROM sites WHERE organization_id = 'org-101';

-- Demo users (owner, admin, supervisors, labour).
DELETE FROM users WHERE organization_id = 'org-101';

-- The demo organization itself.
DELETE FROM organizations WHERE id = 'org-101';

COMMIT;
